name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment variables
      run: |
        echo "Setting up environment variables..."
        # Write the multi-line secret to the .env file
        echo "${{ secrets.ENV_VARS }}" > Todo-application/backend/.env

    - name: Build Backend Docker Image
      run: |
        cd Todo-application/backend
        docker build -t backend:v1.0 .

    - name: Build Frontend Docker Image
      run: |
        cd Todo-application/frontend
        docker build -t frontend:v1.0 .

    - name: RUn docker images
      run: |
        docker network create webapp_network
        docker run -d -p 5000:5000 --name backend --network webapp_network backend:v1.0
        docker run -d -p 3000:3000 --name frontend --network webapp_network frontend:v1.0


