name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Backend Docker Image
      run: |
        cd Todo-application/backend
        docker build -t backend:v1.0 .

    - name: Build Frontend Docker Image
      run: |
        cd Todo-application/frontend
        docker build -t frontend:v1.0 .
